;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mc/mark-next-lines
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ))
