#!/usr/bin/env bash
IFS=$'
'
window_list=($(ratpoison -c windows | grep $1))
count=${#window_list[@]}
unset IFS

if [[ $count -eq 0 ]] ; then
    $2&
elif [[ $count -eq 1 ]]; then
    # echo $window_list
    number=$(printf '%s\n' "${window_list[@]}" | cut -c2)
    ratpoison -c "select $number"
else
    window=$(printf '%s\n' "${window_list[@]}" | rofi -dmenu -i -p "> " -no-custom)

    if [[ "$window" != "" ]]; then
        number=$(echo -e $window | cut -c2)
        ratpoison -c "select $number"
    fi
fi
