#!/usr/bin/env bash

window_list=$(ratpoison -c "windows")
window=$(echo -e "$window_list" | sed 's/URxvt/URxvt terminal/' | rofi -dmenu -i -p "> " -no-custom)

if [[ "$window" != "" ]];
then
  number=$(echo $window | cut -c 2)
  ratpoison -c "select $number"
fi