#!/usr/bin/env bash
notmuch tag -untagged +personal +inbox -- tag:untagged and to:jethrokuan95@gmail.com
notmuch tag -untagged +nus +inbox -- tag:untagged and to:\*@u.nus.edu
notmuch tag -untagged +nus +inbox -- tag:untagged and to:\*@comp.nus.edu.sg
notmuch tag -untagged +nushackers +inbox -- tag:untagged and to:\*@nushackers.org
